/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_firo_lelantus_Lelantus */

#ifndef ORG_FIRO_LELANTUS_LELANTUS_H
#define ORG_FIRO_LELANTUS_LELANTUS_H
#ifdef __cplusplus
extern "C" {
#endif

/*
* Class:     org_firo_lelantus_Lelantus
* Method:    jCreateMintScript
* Signature: (JJJJ)J
*/
JNIEXPORT jstring JNICALL Java_org_firo_lelantus_Lelantus_jCreateMintScript
        (JNIEnv *, jobject, jlong, jstring, jint, jstring);

/*
* Class:     org_firo_lelantus_Lelantus
* Method:    jCreateMintScript
* Signature: (JJJ)J
*/
JNIEXPORT jstring JNICALL Java_org_firo_lelantus_Lelantus_jGetPublicCoin
		(JNIEnv *, jobject, jlong, jstring, jint);

/*
* Class:     org_firo_lelantus_Lelantus
* Method:    jEstimateFee
* Signature: (JJJJ)J
*/
JNIEXPORT jobject JNICALL Java_org_firo_lelantus_Lelantus_jEstimateJoinSplitFee
		(JNIEnv *, jobject, jlong, jboolean, jstring, jobject);

/*
* Class:     org_firo_lelantus_Lelantus
* Method:    jGetMintKeyPath
* Signature: (JJJ)J
*/
JNIEXPORT jint JNICALL Java_org_firo_lelantus_Lelantus_jGetMintKeyPath
		(JNIEnv *, jobject, jlong, jstring, jint);

/*
* Class:     org_firo_lelantus_Lelantus
* Method:    jCreateJMintScript
* Signature: (JJJJJ)J
*/
JNIEXPORT jstring JNICALL Java_org_firo_lelantus_Lelantus_jCreateJMintScript
		(JNIEnv *, jobject, jlong, jstring, jint, jstring, jstring);

/*
* Class:     org_firo_lelantus_Lelantus
* Method:    jCreateSpendScript
* Signature: (JJJJJJJJJ)J
*/
JNIEXPORT jstring JNICALL Java_org_firo_lelantus_Lelantus_jCreateSpendScript
		(JNIEnv *, jobject, jlong, jboolean, jstring, jint, jobject, jstring, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif //ORG_FIRO_LELANTUS_LELANTUS_H
