/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_firo_lelantus_Lelantus */

#ifndef ORG_FIRO_LELANTUS_LELANTUS_H
#define ORG_FIRO_LELANTUS_LELANTUS_H
#ifdef __cplusplus
extern "C" {
#endif

/*
* Class:     org_firo_lelantus_Lelantus
* Method:    jCreateMintCommitment
* Signature: (JJJJ)J
*/
JNIEXPORT jstring JNICALL Java_org_firo_lelantus_Lelantus_jCreateMintCommitment
        (JNIEnv *, jobject, jlong, jstring, jint, jstring);

/*
* Class:     org_firo_lelantus_Lelantus
* Method:    jCreateSpendProof
* Signature: (JJJJJ[JJJJ)J
*/
JNIEXPORT jstring JNICALL Java_org_firo_lelantus_Lelantus_jCreateSpendProof
        (JNIEnv *, jclass, jlong, jstring, jint, jobjectArray, jint, jstring, jstring);

/*
* Class:     org_firo_lelantus_Lelantus
* Method:    jGetSerialNumber
* Signature: (JJJ)J
*/
JNIEXPORT jstring JNICALL Java_org_firo_lelantus_Lelantus_jGetSerialNumber
        (JNIEnv *, jclass, jlong, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif //ORG_FIRO_LELANTUS_LELANTUS_H
